services:
  - type: web
    name: recipe-collection
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: recipe-collection-db
          property: connectionString
      - key: CLOUDINARY_URL
        sync: false

databases:
  - name: recipe-collection-db
    databaseName: recipe_collection
    user: recipe_collection_user