# Generated by Django 3.2.19 on 2023-06-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='headline',
            field=models.CharField(max_length=400),
        ),
    ]
