# Generated by Django 3.2.19 on 2023-07-22 11:48

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_collection', '0002_alter_recipe_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(max_length=200, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='recipe_images'),
        ),
    ]
